spring:
    mail:
       host: localhost
       port: 25
       user:
       password:
       protocol: smtp
       tls: false
       auth: false
       from: classes@localhost

    messageSource:
        cacheSeconds: 1

#swagger:
#    title: classes API
#    description: classes applications and beyond!
#    termsOfServiceUrl: http://jhipster.github.io/
#    contact:
#    license: Apache 2.0
#    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html