server:
    port: 8080

spring:
    profiles: dev

#    datasource:
#        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#        url: jdbc:mysql://localhost:3306/RGSTN2
#        databaseName:
#        databaseType: MYSQL
#        serverName:
#        username: root
#        password:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true

    masterDatasource:
        dataSourceClassName: com.ibm.db2.jcc.DB2SimpleDataSource
        serverName: server name
        portNumber: 3000
        databaseName: dbname
        username: secret password
        password: super secret stuff
        driverType: 4


    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:react
        databaseName:
        databaseType: H2
        serverName:
        username:
        password:

    jpa:
        #database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        #database: MYSQL
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            hibernate.cache.use_query_cache: true
            hibernate.generate_statistics: true

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

    #security:
    #    sessions: always

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: false
    package:
      project: edu.iastate.classes
      domain: edu.iastate.classes.domain
      restdto: edu.iastate.classes.web.rest.dto
    liquibase:
      defaultCatalogName: classes
      defaultSchema: classes
      #excludeTables: T_AUTHORITY,T_PERSISTENT_AUDIT_EVENT,T_PERSISTENT_AUDIT_EVENT_DATA,T_PERSISTENT_TOKEN,T_USER,T_USER_AUTHORITY
    watchdir:
      - target/classes
